---
version: '3.8'
services:
  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - yolo:/data/db
    networks:
      - yolo-network

  backend:
    build: ./backend
    image: backend-image
    container_name: backend
    ports:
      - "5000:5000"
    enviroment: 
      DB_URL: mongodb://database/
    depends_on:
      - mongodb
    networks:
      - yolo-network

  frontend:
    build: ./client
    image: frontend-image
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - yolo-network

networks:
  yolo-network:

volumes:
  yolo:
