#version: '3.9'
services:
  database:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - yolo:/data/db
    networks:
      - yolo-network

  backend:
    build: ./backend
    container_name: backend
    image: niconyango/backend:v1.0.0
    ports:
      - "5000:5000"
    environment:
      # DB_URL: mongodb://database/
      DB_URL: mongodb://mongodb:27017/
    depends_on:
      - database
    networks:
      - yolo-network

  frontend:
    build: ./client
    container_name: frontend
    image: niconyango/frontend:v1.0.0
    ports:
      - "3000:80"
    networks:
      - yolo-network

networks:
  yolo-network:
    name: yolo-network
    driver: bridge

volumes:
  yolo:
    name: yolo
