# PersistentVolumeClaim manifest
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: custom-standard
  
  
