apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  resources:
    requests:
      storage: 1G
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: mongo-pv
