apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: mongo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo-statefulset
    spec:
      containers:
      - name: mongo-statefulset
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
          name: web
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      anotations:
        volume.beta.kubernetes.io/storageclass: "standard"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
