apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-stateful
spec:
  selector:
    matchLabels:
      app: mongo-stateful
  serviceName: mongo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo-stateful
    spec:
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-pvc
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: yolo-ip4
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
